### ISSUE TITLE
Plugin causes errors in fluentd log: no implicit conversion of nil into Hash

### ISSUE THREAD

**Issue by toabi** [kube-logging/fluent-plugin-label-router#16]
**Describe the bug**
We see the following error message in our fluentd logs:

```
2021-06-21 13:41:10 +0000 [warn]: #0 send an error event stream to @ERROR: error_class=TypeError error="no implicit conversion of nil into Hash" location="/usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-label-router-0.2.8/lib/fluent/plugin/out_label_router.rb:78:in `merge'" tag="kubernetes.var.log.containers.i984d793b-3f7d-4347-9120-f429edfeb9fa-redacted-7ef8eac3ba82fc3587fc15f48fe8b767bf865d88f6c6bda869f635e0e1b9d85e.log"
```

Apparently this in in this plugin.

**Steps to reproduce the issue:**

We deployed the banzai logging-operator according to the documentation but ran into this issue: https://github.com/fluent/fluentd/issues/3382

To fix it we wanted to build a own image with fixed resolv gem. But suddenly we are running in this error here which we didn't notice before.

**Expected behavior**
No errors in the fluentd log

**Additional context**
What we "think" happens:

https://github.com/banzaicloud/fluent-plugin-label-router/blob/master/lib/fluent/plugin/out_label_router.rb#L78 this is where the error happens, so probably `@metrics_labels` is `nil`

We don't really know how it can happen. Maybe it always was an issue but is only triggered now because `get_labels` was introduced in https://github.com/banzaicloud/fluent-plugin-label-router/commit/6bebb8cf70ab4fb2554233c724c55c92eea92c70#diff-770a565d029ee0874311cbe0bf8cdc8019ba5728527ee973e29b2caf4ac3eb82R125

Older images of banzai/fluentd don't ship with this change.

**Comment by tomfankhaenel** [comment]
Hi,

i can confirm having the same issue. In my case the issue started appearing after upgrading the banzaicloud logging-operator helm chart from 3.12.0 to 3.13.0.
The new helm chart deploys the fluentd with the image: 'ghcr.io/banzaicloud/fluentd:v1.12.4-alpine-4'.
The 3.12.0 helm chart deployed the fluentd with the image: 'ghcr.io/banzaicloud/fluentd:v1.12.4-alpine-1'

I think the issue was already existing in the "ghcr.io/banzaicloud/fluentd:v1.12.4-alpine-1" image but it was not visible because i could not enable the metrics for fluentd.
I just did some more debugging and found the issue is only occouring once the metrics block for fluentd has been added in the logging CRD of the logging-operator.

**Comment by pepov** [comment]
Sorry we missed this completely!

Could you spot a route in your fluentd config that didn't have a metrics_labels key in it, or where the value was empty? If yes how did it look and what is the corresponding flow for it?

We can fix the conversion but would like to understand how to reproduce first, because right now I can't.

**Comment by pepov** [comment]
It seems to happen when a default route is configured only.
